theme: jekyll-theme-cayman
permalink: title
title: [kontainer.ooo]
description: [Kontainer.ooo is a container-based hosting platform. It simplifies the use of containers in order to create software stacks. Additionally it helps to improve security by encapsulating every part of your application.]
